Numpy

**What is NumPy**

NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

NumPy provides a convenient and efficient way to handle the vast amount of data. NumPy is also very convenient with Matrix multiplication and data reshaping. NumPy is fast which makes it reasonable to work with a large set of data.



convert list into array

In [44]:
import numpy as np

my_list = [1,2,3]
arr = np.asarray(my_list)
arr

array([1, 2, 3])

shape and data type of array using .shape and .dtype

In [45]:
print(arr.shape)
print(arr.dtype)

(3,)
int64


numpy has diff data types than python and you can create one as follows

In [46]:
arr_zero = np.zeros((2,5))
arr_ones = np.ones((3,6))
arr_zero_five = np.arange((6))
arr_spaced = np.linspace(0,10,10)
arr_random = np.random.random((5,5))

print(arr_zero)
print(arr_ones)
print(arr_zero_five)
print(arr_spaced)
print(arr_random)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[0 1 2 3 4 5]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[[0.62219813 0.85364928 0.04508536 0.71487415 0.15180964]
 [0.15572104 0.68528387 0.56609293 0.47843404 0.66511237]
 [0.92592401 0.41118072 0.46941242 0.8285308  0.16466966]
 [0.34162917 0.51371015 0.20681992 0.60012272 0.4255579 ]
 [0.38123001 0.20223433 0.6655839  0.63095073 0.8747681 ]]


two dimensional array

In [47]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

Properties

In [48]:
print(arr1.ndim) #show dimension
print(arr1.itemsize) #prints byte size of element
print(arr1.dtype) #prints data type

arr2 = np.array([[1,2,3],[4,5,6]], dtype = np.float64) #change data type
print(arr2)

arr3 = np.array([[1,2,3],[4,5,6]], dtype = np.complex64) #change data type into complex
print(arr3)

print(arr1.size) # shows size
print(arr1.shape) # shows the shape

print(arr1.reshape(3,2)) #here you can reshape an array too
print(arr1.reshape(6,1))

print(arr1.ravel()) #to flaten array make it one dimension

print(arr1) #still same dimension as its not affected to original array .ravel() fun

print(arr1.min()) #min value
print(arr1.max()) #max value

print(arr1.sum()) #sum all the numbers/ elements from array

#             axis 0
#               |
#             1   2   3
# axis 1 ---  4   5   6

print(arr1.sum(axis = 0)) #sum of all 0 axis
print(arr1.sum(axis = 1)) #sum of all 1 axis

print(np.sqrt(arr1)) #square root of all elements from array

print(arr1.std()) #print standard deviation of arr1

2
8
int64
[[1. 2. 3.]
 [4. 5. 6.]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
6
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
1
6
21
[5 7 9]
[ 6 15]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
1.707825127659933


operations

In [49]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

print(a+b) #sum operation of two arrays
print(a*b) #multipliaction opreation
print(a/b) #division

#matrix multiplication/ matrix product
print(a.dot(b))
print(np.dot(a,b))
print(np.matmul(a,b))
print(np.multiply(a,b)) #simple muliplication

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
