Numpy

**What is NumPy**

NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

NumPy provides a convenient and efficient way to handle the vast amount of data. NumPy is also very convenient with Matrix multiplication and data reshaping. NumPy is fast which makes it reasonable to work with a large set of data.



convert list into array

In [44]:
import numpy as np

my_list = [1,2,3]
arr = np.asarray(my_list)
arr

array([1, 2, 3])

shape and data type of array using .shape and .dtype

In [45]:
print(arr.shape)
print(arr.dtype)

(3,)
int64


numpy has diff data types than python and you can create one as follows

In [46]:
arr_zero = np.zeros((2,5))
arr_ones = np.ones((3,6))
arr_zero_five = np.arange((6))
arr_spaced = np.linspace(0,10,10)
np.random.seed(0) #if you want to fix random numbers by using .seed() your random number will not change again and again as you run code
arr_random = np.random.random((5,5))

print(arr_zero)
print(arr_ones)
print(arr_zero_five)
print(arr_spaced)
print(arr_random)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[0 1 2 3 4 5]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[[0.62219813 0.85364928 0.04508536 0.71487415 0.15180964]
 [0.15572104 0.68528387 0.56609293 0.47843404 0.66511237]
 [0.92592401 0.41118072 0.46941242 0.8285308  0.16466966]
 [0.34162917 0.51371015 0.20681992 0.60012272 0.4255579 ]
 [0.38123001 0.20223433 0.6655839  0.63095073 0.8747681 ]]


two dimensional array

In [47]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

Properties

In [48]:
print(arr1.ndim) #show dimension
print(arr1.itemsize) #prints byte size of element
print(arr1.dtype) #prints data type

arr2 = np.array([[1,2,3],[4,5,6]], dtype = np.float64) #change data type
print(arr2)

arr3 = np.array([[1,2,3],[4,5,6]], dtype = np.complex64) #change data type into complex
print(arr3)

print(arr1.size) # shows size
print(arr1.shape) # shows the shape

print(arr1.reshape(3,2)) #here you can reshape an array too
print(arr1.reshape(6,1))

print(arr1.ravel()) #to flaten array make it one dimension

print(arr1) #still same dimension as its not affected to original array .ravel() fun

print(arr1.min()) #min value
print(arr1.max()) #max value

print(arr1.sum()) #sum all the numbers/ elements from array

#             axis 0
#               |
#             1   2   3
# axis 1 ---  4   5   6

print(arr1.sum(axis = 0)) #sum of all 0 axis
print(arr1.sum(axis = 1)) #sum of all 1 axis

print(np.sqrt(arr1)) #square root of all elements from array

print(arr1.std()) #print standard deviation of arr1

2
8
int64
[[1. 2. 3.]
 [4. 5. 6.]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
6
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
1
6
21
[5 7 9]
[ 6 15]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
1.707825127659933


operations

In [49]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

print(a+b) #sum operation of two arrays
print(a*b) #multipliaction opreation
print(a/b) #division

#matrix multiplication/ matrix product
print(a.dot(b))
print(np.dot(a,b))
print(np.matmul(a,b))
print(np.multiply(a,b)) #simple muliplication

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


Slicing and indexing

In [51]:
np.random.seed(0)
np_rand = np.random.random((3,3))

#here we make one copy of array named np_rand which will help to keep our original array unmodified
#also creating sub arrau
np_sub_rand = np.copy(np_rand[0:3 , 0])
print(np_sub_rand)

#here we have modify into 1000 and also will affect into original one
np_sub_rand[0] = 1000

print(np_sub_rand)

print(np_rand)



# np_arr = np.ones((7, 6))
# np_slice = np.zeros((2,2))
# np_copy = np.copy(np_arr)
# np_slice = np_copy[2,3]
# np_slice[2,3]= [4,5]
# print(np_slice)

np_arr = np.ones((7, 6))
np_slice = np.zeros((2,2))
np_copy = np_arr.copy()
np_copy[2:4 , 3:5] = np_slice

[0.5488135  0.54488318 0.43758721]
[1.00000000e+03 5.44883183e-01 4.37587211e-01]
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]


Insert, append and delete array

In [52]:
np_arr = np.array([[1,2], [6,8]])
print(np_arr)

#here we insert and obj is index number
np_arr_insert = np.insert(arr = np_arr , obj = 1 , values = [3,4] , axis = 0 )
print(np_arr_insert)

#here without using axis we get an single array with append and if we provide axis we get into ndimension
np_arr_append = np.append(arr = np_arr , values = [[3,4], [1,2]])
print(np_arr_append)

#delete element and obj is index
np_arr_delete = np.delete(arr = np_arr , obj = 1 , axis = 1)
print(np_arr_delete)


np_arr = np.array( [[ 20 , 14] , [ 31 , 41] , [ 941 , 678] , [1468 , 121]] )

np_copy1 = np_arr.copy()
np_copy2 = np_arr.copy()
np_copy3 = np_arr.copy()

np_copy1 = np.append( np_copy1 , [ 3,4,5 ] )
np_copy2 = np.insert(np_copy2 ,1 , [ [15,21] , [41,93 ] ] , axis = 0 )
np_copy3 = np.delete(np_copy3 , 0 , 0)


[[1 2]
 [6 8]]
[[1 2]
 [3 4]
 [6 8]]
[1 2 6 8 3 4 1 2]
[[1]
 [6]]
[3 3 5 3 5]
bool


Array logical indexing

In [54]:
#here we want the elements greater than 2 from arr
np_arr= np.array( [[1,2,3], [2,3,5], [1,3,5]] )
np_condarr = np_arr [ np_arr>2 ]
print( np_condarr )
print((np_arr>2).dtype )


np_arr = np.array( [[50,221, 12], [21,30,541], [12,31 ,45]] )
np_log = np_arr[ np_arr >= 30 ]
print(np_log)

[3 3 5 3 5]
bool
[ 50 221  30 541  31  45]


BroadCasting

In [57]:
np_arr = np.array([[2,3], [4,10]])
np_arr_broad = np_arr *5
print(np_arr_broad)

np_five = np.array([[5,5], [5,5]])
np_arr_nobroad = np_arr*np_five
print(np_arr_nobroad)

[[10 15]
 [20 50]]
[[10 15]
 [20 50]]


In [58]:
np_arr_nobroad.shape

(2, 2)